version: '3.9'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app          # Mount current folder for live changes
      - /app/node_modules
    command: npm run dev # Use nodemon if installed
